# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphical_user_interface_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 876)
        MainWindow.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background:transparent;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color:#003814;\n"
"}\n"
"\n"
"#headerContainer {\n"
"    background-color:#00210c;\n"
"}\n"
"\n"
"#frame_11, #frame_4, #frame_16, #frame_13, #cameraSettingsHeaderFrame{\n"
"    background-color:#00210c;\n"
"    border-radius:10px;    \n"
"}\n"
"\n"
"#stageControlContainer {\n"
"    background-color:#017942;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: green;\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-radius: 12px;\n"
"    margin: -8px 0;\n"
"}\n"
"\n"
"\n"
"#led_button_1, #led_button_2, #led_button_3, #led_button_4, #led_button_5, #led_button_6, #led_button_7, #led_button_8, #led_button_9, #led_button_10, #led_button_11, #led_button_12, #led_button_13, #led_button_14, #led_button_15, #led_button_16, #led_button_17, #led_button_18, #led_button_19, #led_button_20, #led_button_21, #led_button_22, #led_button_23, #led_button_24 {\n"
"    width:50px;\n"
"    height:50px;\n"
"    border-radius: 20px;  /* Half of the button\'s width/height */\n"
"    background-color: #919191;\n"
"    font-size: 16px;\n"
"    color: #4CAF50;\n"
"}\n"
"#led_button_1:hover, #led_button_2:hover, #led_button_3:hover, #led_button_4:hover, #led_button_5:hover, #led_button_6:hover, #led_button_7:hover, #led_button_8:hover, #led_button_9:hover, #led_button_10:hover, #led_button_11:hover, #led_button_12:hover, #led_button_13:hover, #led_button_14:hover, #led_button_15:hover, #led_button_16:hover, #led_button_17:hover, #led_button_18:hover, #led_button_19:hover, #led_button_20:hover, #led_button_21:hover, #led_button_22:hover, #led_button_23:hover, #led_button_24:hover {\n"
"    background-color: yellow;\n"
"}\n"
"\n"
"#led_button1:clicked{\n"
"    background-color: yellow;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
